PROJECT_NAME = 'smartnotes'
PROJECT_NAME_CAPITALIZED = 'SmartNotes'
PROJECT_SHORT_DESCRIPTION = 'Natural language text annotation service'
PROJECT_VERSION = '0.0.1'

BIND_HOST = '127.0.0.1'
BIND_PORT = 4000

DATA_PROVIDER_CLIENT_USER_AGENT = (
    f'{PROJECT_NAME_CAPITALIZED}/{PROJECT_VERSION} ({PROJECT_SHORT_DESCRIPTION})'
)

DATA_PROVIDER_CLIENT_HEADERS = {
    'User-Agent': DATA_PROVIDER_CLIENT_USER_AGENT,
}
